### ISSUE TITLE
Unable to autocomplete commands when I use the sudo command

### ISSUE THREAD

**Issue by vndroid** [vmware/photon#1348]
### Describe the bug

Unable to autocomplete commands when I use the sudo command, such as 

```bash
sudo tdnf ...
```

and so on. I can not find out the solutions.

### Reproduction steps

```bash
1. add a new user.
2. add the new user to the sudo list.
3. switch to the new user's account.
4. can not use the bash_completion and the root account also can not use the sudo autocomplete.
```

### Expected behavior

when I use the sudo command, I can use TAB to auto complete the command.

### Additional context

OS version: PhotonOS 4.0 Rev2

**Comment by sshedi** [comment]
After logging into the regular user account, run the following command:
```
complete -F _root_command sudo
```

You can add this to your .bash_profile / .bashrc, and all bash completions work smoothly.
I tested this on my Ph4 vm, working as expected.

**Comment by vndroid** [comment]
Thanks, it works. Will this issue be fixed in the future?

**Comment by sshedi** [comment]
I have made the necessary changes in our bash spec, fixed rpm will be released soon. Thanks.

**Comment by sshedi** [comment]
Fixed in https://github.com/vmware/photon/commit/49769c1c48dcd947cb40711c6e7f7495c9d80092
Please close this bug.

**Comment by Whiteoakrum** [comment]
Good day, where in the 

> After logging into the regular user account, run the following command:
> 
> ```
> complete -F _root_command sudo
> ```
> 
> You can add this to your .bash_profile / .bashrc, and all bash completions work smoothly. I tested this on my Ph4 vm, working as expected.

Good day, where in the .bashrc file to add that line? under which line or before which line ?

**Comment by sshedi** [comment]
No need to do add it anywhere, it's fixed in upstream already.

If at all you want to add it yourself, you can add it anywhere in your bashrc

**Comment by vndroid** [comment]
This issue still exists in PhotonOS 5.0. I hope it can be dealt with as soon as possible.

**Comment by dcasota** [comment]
Hi, there was an issue https://github.com/vmware/photon/issues/1574 a few months ago. Updating bash package + logoff/logon helped. Could you share some data about your setup?

---
fyi tested on latest nightly build, still okay.
```
useradd test -m -g users -G sudo,wheel
echo "test ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
passwd test
```
logout and login with `test` user.
`sudo tdnf ` and press TAB.

<img width="2249" height="431" alt="Image" src="https://github.com/user-attachments/assets/bac93b49-df99-4f93-8753-827a94ce9d7b" />

**Comment by sshedi** [comment]
Thanks for reporting this issue.
Changes made in https://github.com/vmware/photon/commit/49769c1c48dcd947cb40711c6e7f7495c9d80092 was undone by https://github.com/vmware/photon/commit/2386008a951b39340a2c3964b621798b3fa40a64, I'm addressing it.

If you need a quick solution, please modify the file`/usr/share/bash-completion/bash_completion`
Change
```
complete -F _comp_root_command fakeroot gksu gksudo kdesudo really
```
to
```
complete -F _comp_root_command fakeroot gksu gksudo kdesudo really sudo
```

**Comment by vndroid** [comment]
> Thanks for reporting this issue. Changes made in [49769c1](https://github.com/vmware/photon/commit/49769c1c48dcd947cb40711c6e7f7495c9d80092) was undone by [2386008](https://github.com/vmware/photon/commit/2386008a951b39340a2c3964b621798b3fa40a64), I'm addressing it.
> 
> If you need a quick solution, please modify the file`/usr/share/bash-completion/bash_completion` Change
> 
> ```
> complete -F _comp_root_command fakeroot gksu gksudo kdesudo really
> ```
> 
> to
> 
> ```
> complete -F _comp_root_command fakeroot gksu gksudo kdesudo really sudo
> ```

Thanks a lot, it works.

**Comment by sshedi** [comment]
Fixed by: https://github.com/vmware/photon/commit/51d64cdd5a8d5bd27802c813e49a2c9041ee5820
