### ISSUE TITLE
Starting public docker swarm mode service issue with iptables

### ISSUE THREAD

**Issue by nbaillie** [vmware/photon#558]
I just updated to docker 1.12.1 using tdnf and seeing some issues starting swarm services with exposed public ports.

started using:
docker service create --name somecontainer --replicas 1  --publish 80:80 my/container

Im guessing that there are some chains missing perhaps but have not been able to find the correct solution.
Original install was from the 1.0ova.

If i disable iptables auto-config using dockerd --iptables=false  container dose start and run..

Nov 08 21:22:47 photon-iRwyifBuw docker[463]: time="2016-11-08T21:22:47Z" level=info msg="Firewalld running: false"
Nov 08 21:22:47 photon-iRwyifBuw docker[463]: time="2016-11-08T21:22:47.746167673Z" level=error msg="Failed joining ingress sandbox to ingress endpoint: error creating external connectivity netw
ork: Failed to program FILTER chain: iptables failed: iptables --wait -I FORWARD -o docker_gwbridge -j DOCKER: iptables v1.6.0: Couldn't load target `DOCKER':No such file or directory\n\nTry `ip
tables -h' or 'iptables --help' for more information.\n (exit status 2)"

.
.
.
.
Nov 08 21:31:03 photon-iRwyifBuw docker[463]: time="2016-11-08T21:31:03Z" level=info msg="Firewalld running: false"
Nov 08 21:31:03 photon-iRwyifBuw docker[463]: time="2016-11-08T21:31:03Z" level=error msg="setting up rule failed, [-t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 80]:  (iptables f
ailed: iptables --wait -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 80: iptables: No chain/target/match by that name.\n (exit status 1))"

**Comment by YustasSwamp** [comment]
Fixed by the same commit: https://github.com/vmware/photon/commit/44f551306868837374898884058211ac066a47e3

**Comment by nbaillie** [comment]
looks like the commit to the Dev bellow along with the commit: 44f5513 addresses some of the issues i had.
https://github.com/vmware/photon/commit/f57e7856e940d84f6dc4593ca61f621debf25574

I added the Dev Repo and and updated now the Services can start as described in the test case from the Commit above :)
test from commit - "Steps to verify:
  docker swarm init
  docker service create --name my_web --replicas 1 --publish 8080:80 nginx
  curl localhost:8080"

issue is i can't get the service to work externally looks like it wants to bind to ipv6 not sure if thats ok as in has a redirect to ipv4 or not?

i get:
root@photon-iRwyifBuw [ /etc/systemd/network ]# curl localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused
root@photon-iRwyifBuw [ /etc/systemd/network ]# curl :::8080
^C <---hangs here no response

root@photon-iRwyifBuw [ /etc/systemd/network ]# netstat -nat | grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN     
tcp6      72      0 ::1:8080                ::1:35868               CLOSE_WAIT 

Iptables looks like:
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A OUTPUT -j ACCEPT

root@photon-iRwyifBuw [ /etc/systemd/network ]# iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N DOCKER
-N DOCKER-INGRESS
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER-INGRESS
-A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER-INGRESS
-A POSTROUTING -o docker_gwbridge -m addrtype --src-type LOCAL -j MASQUERADE
-A DOCKER-INGRESS -p tcp -m tcp --dport 8080 -j DNAT --to-destination 172.18.0.2:8080
-A DOCKER-INGRESS -j RETURN

**Comment by YustasSwamp** [comment]
try `curl -4 ...`

Can you show me /etc/hosts, please?

**Comment by nbaillie** [comment]
root@photon-iRwyifBuw [ / ]# curl -4 localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused
root@photon-iRwyifBuw [ / ]# more /etc/hosts
154.61.32.154	PubDOC0183224.myfabrix.com PubDOC0183224

127.0.0.1    localhost
root@photon-iRwyifBuw [ / ]#

**Comment by YustasSwamp** [comment]
Interesting.
Need more info:
# uname -a
# ls -la /boot
# journalctl | grep docker  -  after steps `docker swarm init` `docker service start...`

**Comment by nbaillie** [comment]
after rebooting and leaving and recreating the swarm above still not working but i do have more in iptables now.

root@photon-iRwyifBuw [ /etc/systemd/system/docker.service.d ]# curl -4 localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused
root@photon-iRwyifBuw [ /etc/systemd/system/docker.service.d ]# 

root@photon-iRwyifBuw [ /etc/systemd/system/docker.service.d ]# iptables -S
-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o docker_gwbridge -j DOCKER
-A FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT
-A FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP
-A OUTPUT -j ACCEPT
-A DOCKER-ISOLATION -i docker_gwbridge -o docker0 -j DROP
-A DOCKER-ISOLATION -i docker0 -o docker_gwbridge -j DROP
-A DOCKER-ISOLATION -j RETURN
root@photon-iRwyifBuw [ /etc/systemd/system/docker.service.d ]# iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N DOCKER
-N DOCKER-INGRESS
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER-INGRESS
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER-INGRESS
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -o docker_gwbridge -m addrtype --src-type LOCAL -j MASQUERADE
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 172.18.0.0/16 ! -o docker_gwbridge -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A DOCKER -i docker_gwbridge -j RETURN
-A DOCKER-INGRESS -p tcp -m tcp --dport 8080 -j DNAT --to-destination 172.18.0.2:8080
-A DOCKER-INGRESS -j RETURN
root@photon-iRwyifBuw [ /etc/systemd/system/docker.service.d ]#

uname -a
Linux photon-iRwyifBuw 4.4.26-esx #1-photon SMP Mon Oct 24 20:09:22 UTC 2016 x86_64 GNU/Linux
root@photon-iRwyifBuw [ /etc/systemd/system/docker.service.d ]# ls -la /boot
total 25596
drwxr-xr-x  3 root root     4096 Nov 17 15:18 .
drwxr-xr-x 15 root root     4096 Nov 17 15:18 ..
-r--------  1 root root  3229869 Oct 24 19:49 System.map-4.4.26-1.ph1
-rw-r--r--  1 root root   115062 Oct 24 19:49 config-4.4.26-1.ph1
-rw-r--r--  1 root root    79770 Nov 12 06:11 config-esx-4.4.26-2.ph1
lrwxrwxrwx  1 root root        5 Aug 12 04:06 grub -> grub2
drwxr-xr-x  6 root root     4096 Aug 12 04:06 grub2
-rw-------  1 root root 12041892 Oct 24 20:09 initrd.img-4.4.26-1.ph1
-rw-r--r--  1 root root      176 Oct 24 19:49 linux-4.4.26-1.ph1.cfg
-rw-r--r--  1 root root      210 Nov 12 06:11 linux-esx-4.4.26-2.ph1.cfg
lrwxrwxrwx  1 root root       26 Nov 17 15:18 photon.cfg -> linux-esx-4.4.26-2.ph1.cfg
-rw-r--r--  1 root root  1804515 Nov 12 06:11 system.map-esx-4.4.26-2.ph1
-rw-r--r--  1 root root  6200960 Oct 24 19:49 vmlinuz-4.4.26-1.ph1
-rw-r--r--  1 root root  2706240 Nov 12 06:11 vmlinuz-esx-4.4.26-2.ph1
root@photon-iRwyifBuw [ /etc/systemd/system/docker.service.d ]# 


Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28.455847951Z" level=info msg="Listening for connections" addr="[::]:2377" proto=tcp
Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28.456436595Z" level=info msg="Listening for local connections" addr="/var/lib/docker/swarm/control.sock" proto=unix
Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28.457107087Z" level=info msg="34bdb86b7ee4d8ad became follower at term 0"
Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28.457226796Z" level=info msg="newRaft 34bdb86b7ee4d8ad [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]"
Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28.457249613Z" level=info msg="34bdb86b7ee4d8ad became follower at term 1"
Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28.457303252Z" level=info msg="34bdb86b7ee4d8ad is starting a new election at term 1"
Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28.457365253Z" level=info msg="34bdb86b7ee4d8ad became candidate at term 2"
Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28.457381672Z" level=info msg="34bdb86b7ee4d8ad received vote from 34bdb86b7ee4d8ad at term 2"
Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28.457411046Z" level=info msg="34bdb86b7ee4d8ad became leader at term 2"
Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28.457429239Z" level=info msg="raft.node: 34bdb86b7ee4d8ad elected leader 34bdb86b7ee4d8ad at term 2"
Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28.458982670Z" level=info msg="Initializing Libnetwork Agent Local-addr=154.61.32.154 Adv-addr=154.61.32.154 Remote-addr ="
Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28.476931979Z" level=info msg="Initializing Libnetwork Agent Local-addr=154.61.32.154 Adv-addr=154.61.32.154 Remote-addr ="
Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28.482216608Z" level=error msg="Failed to delete stale ingress sandbox: another sandbox delete in progress"
Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28.550445701Z" level=error msg="Could not delete state for endpoint ingress-endpoint from cluster: cannot delete entry as the entry in table endpoint_table with network id 282zxf0jlb1obup804r8dmw9i and key 451316e9f0fc4d471abea8dd39f84b2815a5b48d071bfdcf0e0e04df2a4ebba6 does not exist"
Nov 17 22:18:28 photon-iRwyifBuw kernel: docker_gwbridge: port 1(vethbde53f0) entered disabled state
Nov 17 22:18:28 photon-iRwyifBuw kernel: docker_gwbridge: port 1(vethbde53f0) entered disabled state
Nov 17 22:18:28 photon-iRwyifBuw kernel: docker_gwbridge: port 1(vethbde53f0) entered disabled state
Nov 17 22:18:28 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:28Z" level=info msg="Firewalld running: false"
Nov 17 22:18:28 photon-iRwyifBuw kernel: docker_gwbridge: port 1(veth31a0756) entered forwarding state
Nov 17 22:18:28 photon-iRwyifBuw kernel: docker_gwbridge: port 1(veth31a0756) entered forwarding state
Nov 17 22:18:34 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:34Z" level=info msg="Firewalld running: false"
Nov 17 22:18:34 photon-iRwyifBuw kernel: docker_gwbridge: port 2(veth4f0430b) entered forwarding state
Nov 17 22:18:34 photon-iRwyifBuw kernel: docker_gwbridge: port 2(veth4f0430b) entered forwarding state
Nov 17 22:18:34 photon-iRwyifBuw docker[29097]: time="2016-11-17T22:18:34Z" level=info msg="Firewalld running: false"
Nov 17 22:18:34 photon-iRwyifBuw kernel: docker_gwbridge: port 2(veth4f0430b) entered disabled state
Nov 17 22:18:34 photon-iRwyifBuw kernel: docker_gwbridge: port 2(veth4f0430b) entered forwarding state
Nov 17 22:18:34 photon-iRwyifBuw kernel: docker_gwbridge: port 2(veth4f0430b) entered forwarding state

**Comment by YustasSwamp** [comment]
you use linux-esx-4.4.26-2 kernel.
docker swarm completely fixed in 4.4.31-2

**Comment by nbaillie** [comment]
root@photon-iRwyifBuw [ / ]# tdnf upgrade-to linux-4.4.31-2.ph1.x86_64
the above fixed the problem thanks for your help now all is working.

**Comment by mohitsr76** [comment]
same issue .. tried all of the above steps it still does not expose ports to outside.. curl -4 localhost works but curl localhost hangs..

kernel updated to 4.4.31 

uname -a
Linux sw-mas 4.4.31 #1-photon SMP Tue Nov 22 15:06:04 UTC 2016 x86_64 GNU/Linux

any suggestions.

**Comment by YustasSwamp** [comment]
Can you show me `iptables -S` and `cat /etc/hosts`, please?

**Comment by mohitsr76** [comment]
as below,

root [ /home/boss ]# iptables -S
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-N DOCKER
-N DOCKER-ISOLATION
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p udp -m udp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p udp -m udp --dport 443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -p udp -m udp --dport 8080 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 2377 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 7946 -j ACCEPT
-A INPUT -p udp -m udp --dport 7946 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 4789 -j ACCEPT
-A INPUT -p udp -m udp --dport 4789 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 2375 -j ACCEPT
-A INPUT -p udp -m udp --dport 2375 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 6881 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 800 -j ACCEPT
-A INPUT -p udp -m udp --dport 800 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 800 -j ACCEPT
-A INPUT -p udp -m udp --dport 800 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o docker_gwbridge -j DOCKER
-A FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT
-A FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP
-A OUTPUT -j ACCEPT
-A DOCKER-ISOLATION -i docker_gwbridge -o docker0 -j DROP
-A DOCKER-ISOLATION -i docker0 -o docker_gwbridge -j DROP
-A DOCKER-ISOLATION -j RETURN

root [ /home/boss ]# cat /etc/hosts

Begin /etc/hosts (network card version)

::1 localhost ipv6-localhost ipv6-loopback
127.0.0.1 localhost.localdomain
127.0.0.1	localhost
127.0.0.1	newpho

End /etc/hosts (network card version)

127.0.0.1 sw-mas
